### ISSUE TITLE
Error while processing RunDeepProfiler: RunDeepProfiler has no attribute 'well'

### ISSUE THREAD

**Issue by jamila-griffith** [Arkkienkeli/DeepProfilerExperiments#9]
Hi,

I am running RunDeepProfiler in CellProfiler on linux cluster, on the example data and came across this error. Not sure if this is due to the incorrect code or something else

**Comment by Arkkienkeli** [comment]
Hi @jamila-griffith, you probably need to report that issue that [in the other repository](https://github.com/DistributedScience/Distributed-DeepProfiler).
